from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class Equation:
    """A mathematical expression extracted from the paper."""

    latex: str
    description: str
    page: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "latex": self.latex,
            "description": self.description,
            "page": self.page,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Equation:
        return cls(
            latex=str(data.get("latex", "")),
            description=str(data.get("description", "")),
            page=int(data.get("page", 0)),
        )


@dataclass(slots=True)
class Algorithm:
    """A pseudocode block extracted from the paper."""

    name: str
    pseudocode: str
    page: int
    language_hint: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "pseudocode": self.pseudocode,
            "page": self.page,
            "language_hint": self.language_hint,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Algorithm:
        return cls(
            name=str(data.get("name", "")),
            pseudocode=str(data.get("pseudocode", "")),
            page=int(data.get("page", 0)),
            language_hint=str(data.get("language_hint", "unknown")),
        )


@dataclass(slots=True)
class Figure:
    """A figure reference with optional extracted image artifact path."""

    caption: str
    page: int
    image_path: Path | None

    def to_dict(self) -> dict[str, Any]:
        return {
            "caption": self.caption,
            "page": self.page,
            "image_path": str(self.image_path) if self.image_path is not None else None,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Figure:
        raw_path = data.get("image_path")
        return cls(
            caption=str(data.get("caption", "")),
            page=int(data.get("page", 0)),
            image_path=Path(raw_path) if isinstance(raw_path, str) and raw_path else None,
        )


@dataclass(slots=True)
class Section:
    """A hierarchical section extracted from the paper."""

    title: str
    level: int
    content: str
    page_start: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "level": self.level,
            "content": self.content,
            "page_start": self.page_start,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Section:
        return cls(
            title=str(data.get("title", "")),
            level=int(data.get("level", 1)),
            content=str(data.get("content", "")),
            page_start=int(data.get("page_start", 1)),
        )


@dataclass(slots=True)
class PaperDocument:
    """Structured paper representation consumed by downstream pipeline stages."""

    title: str
    authors: list[str]
    arxiv_id: str | None
    doi: str | None
    year: int | None
    abstract: str

    sections: list[Section]
    equations: list[Equation]
    algorithms: list[Algorithm]
    figures: list[Figure]

    full_text: str
    pdf_path: Path | None

    references: list[str]
    keywords: list[str]
    domain: str = "unknown"

    def to_dict(self) -> dict[str, Any]:
        """Serialize PaperDocument into JSON-safe dictionary."""

        return {
            "title": self.title,
            "authors": list(self.authors),
            "arxiv_id": self.arxiv_id,
            "doi": self.doi,
            "year": self.year,
            "abstract": self.abstract,
            "sections": [section.to_dict() for section in self.sections],
            "equations": [equation.to_dict() for equation in self.equations],
            "algorithms": [algorithm.to_dict() for algorithm in self.algorithms],
            "figures": [figure.to_dict() for figure in self.figures],
            "full_text": self.full_text,
            "pdf_path": str(self.pdf_path) if self.pdf_path is not None else None,
            "references": list(self.references),
            "keywords": list(self.keywords),
            "domain": self.domain,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PaperDocument:
        """Deserialize PaperDocument from dictionary generated by ``to_dict``."""

        raw_pdf_path = data.get("pdf_path")
        return cls(
            title=str(data.get("title", "")),
            authors=[str(author) for author in data.get("authors", [])],
            arxiv_id=str(data["arxiv_id"]) if data.get("arxiv_id") is not None else None,
            doi=str(data["doi"]) if data.get("doi") is not None else None,
            year=int(data["year"]) if data.get("year") is not None else None,
            abstract=str(data.get("abstract", "")),
            sections=[Section.from_dict(item) for item in data.get("sections", [])],
            equations=[Equation.from_dict(item) for item in data.get("equations", [])],
            algorithms=[Algorithm.from_dict(item) for item in data.get("algorithms", [])],
            figures=[Figure.from_dict(item) for item in data.get("figures", [])],
            full_text=str(data.get("full_text", "")),
            pdf_path=Path(raw_pdf_path) if isinstance(raw_pdf_path, str) and raw_pdf_path else None,
            references=[str(reference) for reference in data.get("references", [])],
            keywords=[str(keyword) for keyword in data.get("keywords", [])],
            domain=str(data.get("domain", "unknown")),
        )
